-- ranking テーブルの作成
create table if not exists ranking (
  id bigint generated by default as identity primary key,
  name text not null,
  score integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLSを有効化
alter table ranking enable row level security;

-- 匿名ユーザーに対して読み取りと書き込みを許可するポリシーを作成
create policy "Enable anonymous read access" 
  on ranking for select 
  to anon
  using (true);

create policy "Enable anonymous insert access" 
  on ranking for insert 
  to anon
  with check (true); 