-- 既存のポリシーを削除
drop policy if exists "Enable anonymous read access" on ranking;
drop policy if exists "Enable anonymous insert access" on ranking;
drop policy if exists "Enable anonymous delete access" on ranking;

-- ranking テーブルの作成（既に存在する場合はスキップ）
create table if not exists ranking (
  id bigint generated by default as identity primary key,
  name text not null,
  score integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLSを有効化
alter table ranking enable row level security;

-- 匿名ユーザーに対して読み取りと書き込みを許可するポリシーを作成
create policy "Enable anonymous read access" 
  on ranking for select 
  to anon
  using (true);

create policy "Enable anonymous insert access" 
  on ranking for insert 
  to anon
  with check (true);

-- 匿名ユーザーに対して削除を許可するポリシーを作成
create policy "Enable anonymous delete access" 
  on ranking for delete 
  to anon
  using (true);

-- シーケンスをリセットする関数を作成
create or replace function reset_ranking_id_sequence()
returns void
language plpgsql
security definer
as $$
begin
  -- シーケンスを1から再開
  alter sequence ranking_id_seq restart with 1;
end;
$$;

-- 匿名ユーザーに関数の実行権限を付与
grant execute on function reset_ranking_id_sequence to anon; 